# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    
    MONETIQUE_LOADING_DIRECTORY: '%kernel.project_dir%/public/uploads/monetique/chargements'
    MONETIQUE_EXTRACTION_DIRECTORY: '%kernel.project_dir%/public/uploads/monetique/extractions'
    MONETIQUE_SQL_EXTRACTION: 'select a.CODE AS CODE , a.cli AS CLIENT,a.EMBOS AS NOM_CLIENT,a.ncp AS COMPTE,a.age AS AGENCE,a.dsai AS DATE_SAISIE,a.cuti AS IdentifiantAgentSaisie, b.lib AS "NOM AGENT DE SAISIE" from spprecarte a, evuti b where a.cuti=b.cuti and a.dsai between'
    MONETIQUE_SQL_EXTRACTION_CONDITION: 'and ncp in'

    DB_NAME: '%env(DB_NAME)%'
    DB_USER: '%env(DB_USER)%'
    DB_PASS: '%env(DB_PASS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
